### ISSUE TITLE
Schema file not included in the conda package

### ISSUE THREAD

**Issue by hadim** [conda-forge/jupyter-archive-feedstock#6]
Related issue: https://github.com/hadim/jupyter-archive/issues/29

The PyPi package contains the following file:

```
jupyter_archive/labextension/hadim-jupyter-archive-0.5.4.tgz (5.5 kB)
```

This file contains another file called `archive.json` in `package/schema`.

In the conda build logs I can see this:

```
copying jupyter_archive/labextension/hadim-jupyter-archive-0.5.4.tgz -> build/bdist.linux-x86_64/wheel/jupyter_archive-0.5.4.data/data/share/jupyter/lab/extensions
# ...
  adding 'jupyter_archive-0.5.4.data/data/share/jupyter/lab/extensions/hadim-jupyter-archive-0.5.4.tgz'
```

And the generated conda package indeed contains:

```
  adding 'jupyter_archive-0.5.4.data/data/share/jupyter/lab/extensions/hadim-jupyter-archive-0.5.4.tgz' (5.3 kB)
```

But the archive now does not contain `archive.json` anymore (note the 0.2 kB difference in size).

**Comment by hadim** [comment]
`jupyter-git` uses a different approach: https://github.com/conda-forge/jupyterlab-git-feedstock/blob/master/recipe/build.sh

Do you think we should do the same?

**Comment by hadim** [comment]
ping @conda-forge/jupyterlab @conda-forge/help-nodejs @conda-forge/help-python 

In case someone has an idea.

**Comment by hadim** [comment]
Two relevant discussions:

- https://github.com/jupyterlab/jupyterlab/issues/5672
- https://github.com/conda-forge/conda-forge.github.io/issues/761

**Comment by blink1073** [comment]
I looked at the data_files and it seems correct to me.  If you `pip install foo.tgz` in a fresh conda environment does it write the config file to the right place?

**Comment by hadim** [comment]
Sorry, I don't understand what you mean by `it seems correct` and what is `data_files`?

---

I tried to recreate the issue with both `pip` and `conda` and actually the error also happens with `pip` so it does not seem related to `conda` at the end:

```
# Create test env
conda create -y -n test_env_pip pip jupyterlab nodejs
conda activate test_env_pip

# Install via pip
pip install jupyter-archive

# Build lab extension
jupyter lab build

# Check installed files
ls -l $CONDA_PREFIX/share/jupyter/lab/extensions/
ls -l $CONDA_PREFIX/share/jupyter/lab/schemas/@hadim/jupyter-archive
```

```
# Create test env
conda create -y -n test_env_conda pip jupyterlab nodejs
conda activate test_env_conda

# Install via conda
conda install -y jupyter-archive

# Build lab extension
jupyter lab build

# Check installed files
ls -l $CONDA_PREFIX/share/jupyter/lab/schemas/@hadim/jupyter-archive
```

In both cases, starting `jupyter lab` shows the same error related to the jupyter-archive settings.
